### ISSUE TITLE
Post 상세 페이지 컨텐츠 퍼블리싱

### ISSUE THREAD

**Issue by y0c** [sat10am/sat10am-blog#18]
- [ ] source hightlight theme 변경 
- [ ] markdown html style 조정 (현재 정리 안된 상태)

source hightlight는 원하시는 테마가 있는 분들은 커멘트 남겨주세요

**Comment by DoonDoony** [comment]
DRACULA THEME 을 좋아합니다
근데 흰 배경에는 안 어울릴수도 있을 것 같아요 😭

References
1. https://github.com/dracula/highlightjs
2. https://github.com/iamskok/gatsby-syntax-highlight-dracula (deprecated)
