### ISSUE TITLE
메인 페이지의 포토 슬라이드를 About 페이지로 이전

### ISSUE THREAD

**Issue by DoonDoony** [sat10am/sat10am-blog#3]
메인 페이지 상단의 단체 사진 슬라이드를 About 페이지로 이전하는 것을 제안합니다
비어있는 메인 상단은 unsplash.com 에서 예쁜 이미지를 넣어서 영역을 채운다

**Comment by amorfati0310** [comment]
event 탭으로 해커톤 같은 이벤트 마다 아카이브 하는 것도 좋을 것 같아요 ㅎㅅㅎ
