### ISSUE TITLE
Member 간단 소개 추가 

### ISSUE THREAD

**Issue by y0c** [sat10am/sat10am-blog#36]
한 줄 소개 추가
따로 넣고싶은 말이 있다면 comment 에 남겨주세요

**Comment by amorfati0310** [comment]
+_+ 약간 심심한 것 같아서 
ex) member profile hover되면 한줄 소개 문구가 나온다 던지  프로필쪽 디자인 추가 되면 좋을 것 같네요 ㅎㅅㅎ

**Comment by y0c** [comment]
@amorfati0310 개인정보를 뺄 예정이라서 레이아웃이 전체적으로 변경될 것 같아요. #45

**Comment by DoonDoony** [comment]
이렇게는 이슈 처리가 될 것 같지 않으니
차주에 스터디 하면서 이슈 공유하고, 코멘트로 남길 수 있도록 공지하는것으로 해요 🐶
