### ISSUE TITLE
SAT10AM Slack 

### ISSUE THREAD

**Issue by y0c** [sat10am/sat10am-blog#39]
Blog 관련내용은 Hackerton 때 만들어놓은 Slack을 활용하면 어떨까요? 
관련 Issue나 PR 들 channel 에 연결하면 확인하기 편할거같아서 생각해봤어요 🧐
Comment로 의견남겨주세요

**Comment by DoonDoony** [comment]
Slack Hook 을 이용해서 빌드 결과나 배포 결과를 연동해도 좋을 것 같아요

**Comment by godori** [comment]
슬랙 채널 연동도 좋고, Netlify 메일로 배포 할때마다 오는 설정도 간단하게 되더라구요. 
슬랙은 전체 기록용으로, 메일은 노티용으로
둘다 하면 좋을 것 같습니다.

**Comment by DoonDoony** [comment]
@godori 님이 모든 사용자에 대한 Owner 권한 부여하고
방금 Owner 권한으로 Webhook 세팅 하는 것으로 확인했기 때문에
해당 내용 Close 합니다. 

추가적인 사항은 다시 ISSUE 생성 부탁 드립니다
