### ISSUE TITLE
개인정보 공개 범위

### ISSUE THREAD

**Issue by godori** [sat10am/sat10am-blog#45]
사진, 실명, 위치 등의 민감한 개인 정보 게재에 대해서는 논의를 했으면 하는데 어떤가요?
일단 이슈 등록만 해둘게요.

**Comment by y0c** [comment]
네 해커톤 할때는 노션에 있는걸 그대로 옮겨두었는데 개인정보는 지워야 할 것 같네요.

**Comment by DoonDoony** [comment]
저도 실명과 주소 문제로 sat10am 노션 페이지를 비공개로 설정해 둔 부분이라
규칙만 정할 수 있으면 같은 규칙을 적용해서 sat10am 노션 페이지도 공개로 전환하고 싶습니다 🙏

**Comment by y0c** [comment]
Github Profile에 있는 사진하고 username + 간단한 소개정도 남기고 About 페이지에 들어가는 사진을 지우면 괜찮을까요? 😮

**Comment by godori** [comment]
단체사진 하나는 블러처리해서 가운데 로고 박으면 배경으로 쓸 수 있을거 같아요
