### ISSUE TITLE
Netlify with Slack Integration

### ISSUE THREAD

**Issue by DoonDoony** [sat10am/sat10am-blog#46]
빌드나 배포 알림을 슬랙 채널에 Hook 으로 연동하면 좋을 것 같습니다
채널 이름은 release-log 로 하려고 합니다

**Comment by amorfati0310** [comment]
좋습니당 👍

**Comment by DoonDoony** [comment]
별도의 코드 수정 없이 Netlify 환경 설정에서 처리 완료 했습니다
Webhook 의 종류는 아래와 같습니다

1. 배포 시작
2. 배포 성공
3. 배포 실패

Notification 은 **#deploy-log** 채널로 전달되니 참고 바랍니다
해당 건 처리 완료하여 Resolve 합니다
