### ISSUE TITLE
Header Design 변경

### ISSUE THREAD

**Issue by y0c** [sat10am/sat10am-blog#47]
* Logo 만 변경 
* Background 검은색 + 하얀색 로고 
* Background 노란색 + 검은색 로고 

생각해본건 3가지인데 다른의견이나 저중에 하나 골라주세요 ✅

**Comment by y0c** [comment]
PR을 올려주시면 더 좋아요 !

**Comment by DoonDoony** [comment]
저는 다크테마를 좋아하기 때문에 검+흰 조합으로 PR을 올려볼게요

**Comment by y0c** [comment]
@DoonDoony 넵 로고는 노션에 있는거 사용하면 될것같아요

**Comment by amorfati0310** [comment]
https://www.pinterest.co.kr/pin/556124253984459260/
투명으로 배경에 올라와 있는 형태도 괜찮을 것 같아요 :D

**Comment by y0c** [comment]
@amorfati0310 네 저런식도 괜찮은 것 같아요! PR을 ㅎㅎ

**Comment by jwooss** [comment]
저는 두번째 검흰조합에 한표요ㅎㅎ
