### ISSUE TITLE
Namechaep A / CNAME 레코드 추가

### ISSUE THREAD

**Issue by DoonDoony** [sat10am/sat10am-blog#66]
cms.sat10am.dev 서브 도메인으로의 라우팅 처리가 필요하여
Namecheap DNS 설정을 변경하고, A / CNAME 레코드를 추가 합니다

## AS-IS
Namecheap Custom Domain Configuration

## TO-BE
Namecheap Custom Domain Configuration → Namechaep Basic DNS

**Comment by y0c** [comment]
처리된 이슈라 닫겠습니다! 🙂
